# kiro-classification: public
"""The Control_Plane request surface: eight operations, one authorizer, one not-found response.

`ROUTES` is the operation table (R6.1) and every entry carries `AWS_IAM` (R6.3, R6.22).
`ControlPlaneApi` dispatches onto a `SessionOperations` implementation, resolving the Session inside
the caller's own Tenant partition for every route that names one, so the fixed not-found response
(R6.9) is reached by construction rather than by each operation remembering to.

`NOT_FOUND_RESPONSE` is exported as the constant it is rather than behind a builder, because the
guarantee R6.9 asks for is that there is exactly one of it.
"""

from control_plane.api.admission import (
    ADMISSION_ERROR_CODE,
    AUTO_RESUME_FIELD,
    IDLE_SECONDS_FIELD,
    MAX_DURATION_FIELD,
    SUSPENDED_SECONDS_FIELD,
    AdmissionPolicy,
    AdmittedLimits,
    SessionAdmissionRejected,
    admit_session_creation,
)
from control_plane.api.connection import (
    ConnectionOperations,
    ConnectionUnavailable,
    connection_payload,
)
from control_plane.api.creation import (
    EXECUTION_NAME_PREFIX,
    EXPOSED_PORTS_FIELD,
    CreatedSession,
    CreationOperations,
    CreationSettings,
    CreationWait,
    ExecutionNameError,
    NoCreationWait,
    OrchestrationStart,
    OrchestrationStarter,
    SessionRowStore,
    SessionRowWriter,
    creation_payload,
    execution_name_for,
    new_session_id,
    orchestration_start_for,
)
from control_plane.api.creation_wait import (
    POLL_INTERVAL_SECONDS,
    POLL_JITTER_SECONDS,
    RESPONSE_MARGIN_SECONDS,
    CreationContract,
    CreationWaitSettings,
    PollingCreationWait,
    SessionProvisioningFailed,
    wait_for_contract,
)
from control_plane.api.errors import (
    FIXED_HEADERS,
    FORBIDDEN_RESPONSE,
    NOT_FOUND_BODY,
    NOT_FOUND_RESPONSE,
    ControlPlaneError,
    HttpResponse,
    MalformedRequest,
    OperationNotImplemented,
    SessionNotFound,
    UnauthenticatedRequest,
    error_response,
    forbidden,
    json_response,
    not_found,
)
from control_plane.api.handlers import (
    OPERATION_METHODS,
    ControlPlaneApi,
    NotImplementedOperations,
    OperationRequest,
    OperationResult,
    SessionOperations,
    lambda_entrypoint,
)
from control_plane.api.lookup import SessionLookup, resolve_session
from control_plane.api.request import (
    principal_for,
    request_body,
    request_method_and_path,
    verified_caller_identity,
)
from control_plane.api.resolution import (
    AFFINITY_KEY_FIELD,
    DEFAULT_BINDING_MAX_AGE_SECONDS,
    LOSER_BRANCHES,
    MAX_CLAIM_ATTEMPTS,
    RESOLUTION_FIELD,
    BindingConditionFailed,
    BindingSettings,
    BindingStore,
    InvalidAffinityKey,
    LoserBranch,
    ResolutionDidNotSettle,
    ResolutionOperations,
    ResolutionOutcome,
    binding_for,
    digest_of_requested_affinity_key,
    resolution_payload,
)
from control_plane.api.routes import (
    AUTHORIZATION_TYPE,
    OPERATIONS_NAMING_A_SESSION,
    ROUTES,
    ROUTES_BY_OPERATION,
    SESSION_ID_PARAMETER,
    Operation,
    RouteDefinition,
    route_for,
    route_for_key,
)

__all__ = [
    "ADMISSION_ERROR_CODE",
    "AFFINITY_KEY_FIELD",
    "AUTHORIZATION_TYPE",
    "AUTO_RESUME_FIELD",
    "DEFAULT_BINDING_MAX_AGE_SECONDS",
    "EXECUTION_NAME_PREFIX",
    "EXPOSED_PORTS_FIELD",
    "FIXED_HEADERS",
    "FORBIDDEN_RESPONSE",
    "IDLE_SECONDS_FIELD",
    "LOSER_BRANCHES",
    "MAX_CLAIM_ATTEMPTS",
    "MAX_DURATION_FIELD",
    "NOT_FOUND_BODY",
    "NOT_FOUND_RESPONSE",
    "OPERATIONS_NAMING_A_SESSION",
    "OPERATION_METHODS",
    "POLL_INTERVAL_SECONDS",
    "POLL_JITTER_SECONDS",
    "RESOLUTION_FIELD",
    "RESPONSE_MARGIN_SECONDS",
    "ROUTES",
    "ROUTES_BY_OPERATION",
    "SESSION_ID_PARAMETER",
    "SUSPENDED_SECONDS_FIELD",
    "AdmissionPolicy",
    "AdmittedLimits",
    "BindingConditionFailed",
    "BindingSettings",
    "BindingStore",
    "ConnectionOperations",
    "ConnectionUnavailable",
    "ControlPlaneApi",
    "ControlPlaneError",
    "CreatedSession",
    "CreationContract",
    "CreationOperations",
    "CreationSettings",
    "CreationWait",
    "CreationWaitSettings",
    "ExecutionNameError",
    "HttpResponse",
    "InvalidAffinityKey",
    "LoserBranch",
    "MalformedRequest",
    "NoCreationWait",
    "NotImplementedOperations",
    "Operation",
    "OperationNotImplemented",
    "OperationRequest",
    "OperationResult",
    "OrchestrationStart",
    "OrchestrationStarter",
    "PollingCreationWait",
    "ResolutionDidNotSettle",
    "ResolutionOperations",
    "ResolutionOutcome",
    "RouteDefinition",
    "SessionAdmissionRejected",
    "SessionLookup",
    "SessionNotFound",
    "SessionOperations",
    "SessionProvisioningFailed",
    "SessionRowStore",
    "SessionRowWriter",
    "UnauthenticatedRequest",
    "admit_session_creation",
    "binding_for",
    "connection_payload",
    "creation_payload",
    "digest_of_requested_affinity_key",
    "error_response",
    "execution_name_for",
    "forbidden",
    "json_response",
    "lambda_entrypoint",
    "new_session_id",
    "not_found",
    "orchestration_start_for",
    "principal_for",
    "request_body",
    "request_method_and_path",
    "resolution_payload",
    "resolve_session",
    "route_for",
    "route_for_key",
    "verified_caller_identity",
    "wait_for_contract",
]
